apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: us78j4za5-nodejs
  janus-idp.io/tekton: us78j4za5-nodejs
  backstage.io/kubernetes-id: us78j4za5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: us78j4za5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
